name: Lint
on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - run: pip install flake8>=4.0.1
      - run: pip install black>=22.3.0
      - run: pip install isort>=5.9.3
      - run: make lint