name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: '3.10'
          architecture: x64
    - run: python -m pip install --upgrade pip
    - run: pip install flit==3.7.1
    - name: Build and publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: flit publish